Navbar and offcanavas issue solved
pooranjoyb/BeatBridge pull request #50
Opened 2023-12-14 17:49 UTC by ShivamKmishra09

Navbar made sticky with background similar to body. Offcanavas issue fixed. Its background , font and font color changed.

2023-12-14 18:08 UTC, pooranjoyb requested changes
Everything is fine, just make minor changes on the hovering the `links` inside the `Offcanvas Navbar`, also please don't change the `Glass-Morphism` effect that was before in the Navbar, 

Just update the hover effect, add a basic transition-duration and make sure to revert to `GlassMorphism` for the Navbar

2023-12-14 18:11 UTC, ShivamKmishra09 commented
Okay, I will do that , thanks

On Thu, 14 Dec, 2023, 11:38 pm Pooranjoy Bhattacharya, <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Everything is fine, just make minor changes on the hovering the links
> inside the Offcanvas Navbar, also please don't change the Glass-Morphism
> effect that was before in the Navbar,
>
> Just update the hover effect, add a basic transition-duration and make
> sure to revert to GlassMorphism for the Navbar
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pooranjoyb/BeatBridge/pull/50#pullrequestreview-1782413518>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5PQDSNWXZWS57YCXFCKFSTYJM6DPAVCNFSM6AAAAABAVHQW5WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBSGQYTGNJRHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-15 17:51 UTC, pooranjoyb commented
> Okay, I will do that , thanks

Nice Work :) @ShivamKmishra09

2023-12-15 17:51 UTC, pooranjoyb approved these changes

2023-12-15 17:52 UTC, merged